### ISSUE TITLE
How to upload file with same name but not overwrite?

### ISSUE THREAD

**Issue by cogiakk54** [zkoss/zkckeditor#31]
I use the file upload function in insert image, but every time I upload a file with the same name it will overwrite the old file.
How do I do file uploaders using alternate names?
For example:
+ I upload a file named test.png, 
    if a file name test.png already exists, it will change to test(<1-> n>).png or <javatime_stamp>_test.png like 12436456457_test.png

I tried to fix it in the Ckeditor.java file then rebuild and it succeeded, but I don't think it was good.
in line 470
`fileName = FilenameUtils.getName(fileName);`
to
`fileName = new java.util.Date().getTime() +"_"+FilenameUtils.getName(fileName);`
So is there a way to not have to edit the ckez source code and still be able to upload files with the same name but not overwrite?

**Comment by cor3000** [comment]
You can implement a custom the [CkezFileWriter](https://github.com/zkoss/zkckeditor/blob/master/ckez/src/main/java/org/zkforge/ckez/CkezFileWriter.java)

Here the [default implementation] (https://github.com/zkoss/zkckeditor/blob/v4.14.0.0/ckez/src/main/java/org/zkforge/ckez/CKeditor.java#L457-L482) - It doesn't do complex things, and that's were you can check for existing files and customize the filename and the url returned)

It looks like you were already at the right place, maybe you just missed the setFileWriter method.

**Comment by cogiakk54** [comment]
a, tks you, it's work :3
