### ISSUE TITLE
4.16.2.0-jakarta still depends on javax

### ISSUE THREAD

**Issue by khcyt** [zkoss/zkckeditor#36]
Hi,

please check build process. At the moment imports in CkezUploadExtension.java still refer to javax and not to jakarta.

Regards
Kai

**Comment by hawkchen** [comment]
After I check the source of CkezUploadExtension and ckeditor's pom.xml. I don't find any javax related code. Could you provide more specific details like line number or anything else? what error message do you see?

**Comment by khcyt** [comment]
I have downloaded zk-CKEditor-bin-4.16.2.0-jakarta.zip and zk-CKEditor-src-4.16.2.0-jakarta.zip.
In file CkezUploadExtension.java i see in lines 24..27 import javax.servlet.ServletContext an so on.
I put ckez.jar in web-inf/lib folder.

If i start my application i get an exception

Failed to invoke class org.zkforge.ckez.WebAppInit
java.lang.NoClassDefFoundError: javax/servlet/ServletResponse
	at org.zkforge.ckez.WebAppInit.init(WebAppInit.java:29)
	at org.zkoss.zk.ui.util.Configuration.invokeWebAppInits(Configuration.java:781)
	at org.zkoss.zk.ui.impl.AbstractWebApp.init(AbstractWebApp.java:214)
	...

**Comment by hawkchen** [comment]
Thanks. I can confirm the zip content is wrong.
You can download correct jar and source from our maven repository https://mavensync.zkoss.org/maven2/org/zkoss/zkforge/ckez/4.16.2.0-jakarta/

**Comment by khcyt** [comment]
Thanks for the information. It is now working as expected.
Best regards
Kai
